_target_: ctd.data_modeling.models.SAE.gnode.gNODELatentSAE
dataset: PClicks

# DO NOT MOVE ORDER OF KEYS IN DICTS

encoder_size: 100
encoder_window: -1

heldin_size: 300
heldout_size: 350   # SUM of simulator's 'heldout_size' + 'heldin_size'
latent_size: 2
input_size: 3

dropout: 0.05

vf_hidden_size: 64
vf_num_layers: 3
gating_hidden_size: 64
gating_num_layers: 2

lr: 2e-3

weight_decay: 0
alpha: 0.1
output_nonlinearity: None