import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable
from scipy import stats

def analyze_parameter_dependencies(csv_filepath, output_filepath=None, only_linear=False, color_lin=False, 
                                  high_res=True, fig_width=24, fig_height=None, from_model="node",
                                  plot_individual=False):
    """
    Create an array of scatter plots showing dependencies between different metrics,
    with color coding for various parameters and marker types for model types.
    Also adds error bars for data points with the same parameter value and model type.
    
    Parameters:
    - csv_filepath: Path to the CSV file generated by the parsing function
    - output_filepath: Path to save the generated figure (if None, will show instead)
    - only_linear: If True, only include rows where output_nonlinearity is nan
    - color_lin: Color scheme option for nonlinearity
    - high_res: If True, use higher DPI for better resolution
    - fig_width: Width of the figure in inches
    - fig_height: Height of the figure in inches (if None, calculated based on parameters)
    - from_model: Which model's latent size parameter to use ("node", "gru", "gnode")
    - plot_individual: If True, plot individual points instead of aggregated statistics
    
    Returns:
    - The generated figure
    """
    # Read the CSV file
    df = pd.read_csv(csv_filepath)
    
    if only_linear:
        # select all rows where the output nonlinearity is nan
        df = df[df["_output_nonlinearity"].isna()]
    
    # Check if required columns exist
    required_columns = ['rate_r2', 'state_r2', 'co-bps', 'cycle_con', 'model']
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")
    
    # Define parameters to analyze (rows in the plot)
    if from_model == "gru":
        latent_param = '20250413_PClicks_NoisyGRU_final2_latent_size'
    elif from_model == "node":
        latent_param = '20250407_PC_NODE_grid_final_latent_size'
    elif from_model == "gnode":
        latent_param = '20250412_PC_gNODE_sweep_latent_size'
        
    parameters = [latent_param,'_n_heldin', '_vf_hidden_size', '_output_nonlinearity']
    # Check if these parameters exist in the dataframe, remove any that don't
    parameters = [param for param in parameters if param in df.columns]
    if not parameters:
        raise ValueError("None of the specified parameters exist in the dataframe")
    
    # Define x-y metric pairs for the plots (columns in the plot)
    metric_pairs = [
        ('state_r2', 'rate_r2'),     # x, y
        ('cycle_con', 'co-bps'),      # x, y
        ('co-bps', 'rate_r2'),        # x, y
        ('cycle_con', 'state_r2')    # x, y
    ]
    
    # Define marker styles for model types
    model_markers = {
        'node': 'o',    # circle
        'gnode': 's',   # square
        'gru': '^',     # triangle
        'fr': 'D',      # diamond
        'unknown': 'x'  # x
    }
    
    # Set DPI based on high_res flag
    dpi = 240 if high_res else 120
    
    # Adjust figure height if not specified
    if fig_height is None:
        fig_height = 5 * len(parameters)
    
    # Create the figure and subplots grid with space for colorbars
    if len(parameters) > 1:
        fig, axes = plt.subplots(len(parameters), len(metric_pairs), 
                                figsize=(fig_width, fig_height),
                                dpi=dpi,
                                gridspec_kw={'width_ratios': [1] * len(metric_pairs)})
    else:
        # Special case for one parameter
        fig, axes = plt.subplots(len(parameters), len(metric_pairs), 
                                figsize=(fig_width, fig_height),
                                dpi=dpi,
                                gridspec_kw={'width_ratios': [1] * len(metric_pairs)})
        axes = np.array([axes])  # Ensure 2D
    
    # Set a fixed color map for categorical _output_nonlinearity
    if color_lin:
        categorical_colors = {np.nan: 'green', "torch.nn.functional.softplus": "green"}
    else:
        categorical_colors = {np.nan: 'green', "torch.nn.functional.softplus": "red"}
    
    # For the latent size parameter, normalize within each model
    if latent_param in df.columns:
        # Create a new column for normalized latent size
        df['normalized_latent_size'] = np.nan
        
        # For each model, normalize its latent sizes
        for model_type in df['model'].unique():
            model_data = df[df['model'] == model_type]
            if not model_data.empty and not model_data[latent_param].isna().all():
                # Get the maximum latent size for this model
                max_latent = model_data[latent_param].max()
                if max_latent > 0:  # Avoid division by zero
                    # Calculate normalized values (0 to 1)
                    mask = (df['model'] == model_type)
                    df.loc[mask, 'normalized_latent_size'] = df.loc[mask, latent_param] / max_latent
    
    # Dictionary to store colormaps for each parameter
    colormaps = {}
    
    # Process each parameter (row)
    for i, param in enumerate(parameters):
        # Special handling for latent size parameter - use normalized values
        if param == latent_param:
            param_to_use = 'normalized_latent_size'
            numeric_param = True
        elif param == "_output_nonlinearity":
            param_to_use = param
            numeric_param = False
        else:
            param_to_use = param
            # Convert parameter to numeric if possible for color mapping
            try:
                df[param_to_use] = pd.to_numeric(df[param_to_use])
                numeric_param = True
            except (ValueError, TypeError):
                numeric_param = False
        
        # Set up colormap for numeric parameters
        if numeric_param:
            norm = Normalize(vmin=df[param_to_use].min(), vmax=df[param_to_use].max())
            cmap = plt.cm.viridis
            sm = ScalarMappable(cmap=cmap, norm=norm)
            sm.set_array([])
            
            # Store the colormap for this parameter
            colormaps[param] = {'norm': norm, 'cmap': cmap, 'sm': sm}
        
        # Process each metric pair (column)
        for j, (x_metric, y_metric) in enumerate(metric_pairs):
            ax = axes[i, j]
            
            # For categorical _output_nonlinearity, we'll use a different approach
            if param == "_output_nonlinearity":
                # Get unique values for this parameter
                unique_values = df[param].unique()
                
                # Keep track of what we've labeled
                labeled_values = set()
                
                # For each model type
                for model_type, marker in model_markers.items():
                    model_data = df[df['model'] == model_type]
                    if model_data.empty:
                        continue
                    
                    # For each nonlinearity value
                    for val in model_data[param].unique():
                        if isinstance(val, str):
                            val_data = model_data[model_data[param] == val]
                        else:
                            val_data = model_data[model_data[param].isna()]
                        
                        if len(val_data) == 0:
                            continue
                            
                        # Set color based on the nonlinearity type
                        color = categorical_colors.get(val, 'gray')  # Default to gray if not in our map
                        
                        # Create a label that combines model type and nonlinearity, but only once per value
                        label = None
                        if f"{model_type}-{val}" not in labeled_values:
                            label = f"{model_type} - {val}"
                            labeled_values.add(f"{model_type}-{val}")
                        
                        if plot_individual:
                            # Plot individual points
                            ax.scatter(
                                val_data[x_metric], 
                                val_data[y_metric],
                                marker=marker,
                                s=100,
                                alpha=0.7,
                                color=color,
                                edgecolors='k',
                                linewidths=0.5,
                                label=label
                            )
                            continue
                        
                        # If we have enough points for statistics (at least 2)
                        if len(val_data) >= 2:
                            # Calculate mean and standard error for both x and y
                            x_mean = val_data[x_metric].mean()
                            y_mean = val_data[y_metric].mean()
                            x_sem = val_data[x_metric].std() / np.sqrt(len(val_data))
                            y_sem = val_data[y_metric].std() / np.sqrt(len(val_data))
                            
                            # Plot error bars if there's variance
                            if x_sem > 0 or y_sem > 0:
                                ax.errorbar(x_mean, y_mean, 
                                           xerr=x_sem, yerr=y_sem,
                                           fmt='none', ecolor=color, capsize=3, 
                                           alpha=0.7, zorder=5)
                                
                                # Add a larger marker at the mean point for visibility
                                ax.scatter(x_mean, y_mean, 
                                          marker=marker, s=150, color=color, 
                                          edgecolors='black', linewidths=1.5,
                                          alpha=1.0, zorder=6,
                                          label=label)
                            else:
                                # If no variance, just plot the point
                                ax.scatter(x_mean, y_mean, 
                                          marker=marker, s=150, color=color, 
                                          edgecolors='black', linewidths=1.5,
                                          alpha=1.0, zorder=6,
                                          label=label)
                        elif len(val_data) == 1:
                            # If only one point, just plot it
                            ax.scatter(val_data[x_metric].iloc[0], val_data[y_metric].iloc[0], 
                                      marker=marker, s=150, color=color, 
                                      edgecolors='black', linewidths=1.5,
                                      alpha=1.0, zorder=6,
                                      label=label)
                
                # # Add a legend for this specific plot if we have nonlinearity values
                # if unique_values.size > 0 and j == 0:  # Only add legend to first column for clarity
                #     ax.legend(loc='lower right', fontsize=8)
            else:
                # For numeric parameters with error bars
                for model_type, marker in model_markers.items():
                    model_data = df[df['model'] == model_type]
                    if model_data.empty:
                        continue
                    
                    if numeric_param:
                        # If plotting individual points
                        if plot_individual:
                            # Ensure we have the parameter values for coloring
                            if param == latent_param:
                                # For latent size parameter, use normalized values
                                color_values = model_data['normalized_latent_size']
                            else:
                                color_values = model_data[param_to_use]
                            
                            # Plot individual points with proper color mapping
                            scatter = ax.scatter(
                                model_data[x_metric], 
                                model_data[y_metric],
                                c=color_values,
                                cmap=colormaps[param]['cmap'],
                                norm=colormaps[param]['norm'],
                                marker=marker,
                                s=100,
                                alpha=0.7,
                                edgecolors='k',
                                linewidths=0.5,
                                label=model_type
                            )
                            continue
                        
                        # Group by parameter value to calculate means and errors
                        if param == latent_param:
                            # For latent size, group by the original parameter but use normalized values for color
                            param_groups = model_data.groupby(param)
                        else:
                            param_groups = model_data.groupby(param_to_use)
                        
                        # For each unique parameter value
                        for param_value, group in param_groups:
                            
                            # Get color for this parameter value
                            if param == latent_param:
                                # For latent size parameter, use the normalized value for coloring
                                norm_value = group['normalized_latent_size'].iloc[0]
                                color = colormaps[param]['cmap'](colormaps[param]['norm'](norm_value))
                            else:
                                color = colormaps[param]['cmap'](colormaps[param]['norm'](param_value))
                            
                            if len(group) >= 2:  # Only calculate statistics if we have at least 2 points
                                # Calculate mean and standard error
                                x_mean = group[x_metric].mean()
                                y_mean = group[y_metric].mean()
                                x_sem = group[x_metric].std() / np.sqrt(len(group))
                                y_sem = group[y_metric].std() / np.sqrt(len(group))
                                
                                # Plot error bars if there's variance
                                if x_sem > 0 or y_sem > 0:
                                    ax.errorbar(x_mean, y_mean, 
                                               xerr=x_sem, yerr=y_sem,
                                               fmt='none', ecolor=color, capsize=3, 
                                               alpha=0.7, zorder=5)
                                    
                                    # Add a larger marker at the mean point for visibility
                                    ax.scatter(x_mean, y_mean, 
                                              marker=marker, s=150, color=color, 
                                              edgecolors='black', linewidths=1.5,
                                              alpha=1.0, zorder=6)
                                else:
                                    # No variance
                                    ax.scatter(x_mean, y_mean, 
                                              marker=marker, s=150, color=color, 
                                              edgecolors='black', linewidths=1.5,
                                              alpha=1.0, zorder=6)
                            elif len(group) == 1:
                                # Just plot the single point
                                ax.scatter(group[x_metric].iloc[0], group[y_metric].iloc[0], 
                                          marker=marker, s=150, color=color, 
                                          edgecolors='black', linewidths=1.5,
                                          alpha=1.0, zorder=6)
                    else:
                        # Group by unique values if categorical (other than _output_nonlinearity)
                        for val in model_data[param].unique():
                            val_data = model_data[model_data[param] == val]
                            
                            if plot_individual:
                                # For non-numeric parameters, use a consistent color
                                ax.scatter(
                                    val_data[x_metric], 
                                    val_data[y_metric],
                                    marker=marker,
                                    s=100,
                                    alpha=0.7,
                                    edgecolors='k',
                                    linewidths=0.5,
                                    label=f"{model_type} - {param}={val}"
                                )
                                continue
                            
                            # If we have enough points for statistics (at least 2)
                            if len(val_data) >= 2:
                                # Calculate mean and standard error
                                x_mean = val_data[x_metric].mean()
                                y_mean = val_data[y_metric].mean()
                                x_sem = val_data[x_metric].std() / np.sqrt(len(val_data))
                                y_sem = val_data[y_metric].std() / np.sqrt(len(val_data))
                                
                                # Plot error bars if there's variance
                                if x_sem > 0 or y_sem > 0:
                                    ax.errorbar(x_mean, y_mean, 
                                               xerr=x_sem, yerr=y_sem,
                                               fmt='none', ecolor='black', capsize=3, 
                                               alpha=0.7, zorder=5)
                                    
                                    # Add a larger marker at the mean point for visibility
                                    ax.scatter(x_mean, y_mean, 
                                              marker=marker, s=150, color='black', 
                                              edgecolors='black', linewidths=1.5,
                                              alpha=1.0, zorder=6)
                                else:
                                    # Just plot the mean point if no variance
                                    ax.scatter(x_mean, y_mean, 
                                              marker=marker, s=150, color='black', 
                                              edgecolors='black', linewidths=1.5,
                                              alpha=1.0, zorder=6)
                            elif len(val_data) == 1:
                                # Just plot the single point
                                ax.scatter(val_data[x_metric].iloc[0], val_data[y_metric].iloc[0], 
                                          marker=marker, s=150, color='black', 
                                          edgecolors='black', linewidths=1.5,
                                          alpha=1.0, zorder=6)
            
            # First row gets title
            if i == 0:
                ax.set_title(f"{y_metric} vs {x_metric}", fontsize=14)
            
            # Last row gets x-label
            if i == len(parameters) - 1:
                ax.set_xlabel(x_metric, fontsize=12)
            
            # First column gets y-label
            if j == 0:
                if param == latent_param:
                    ax.set_ylabel(f"Normalized {param.split('_')[-1]}", fontsize=12)
                else:
                    ax.set_ylabel(param, fontsize=12)
            
            # Add grid
            ax.grid(True, linestyle='--', alpha=0.6)
    
    # Add colorbars for numeric parameters on the right side of the figure
    for i, param in enumerate(parameters):
        if param == latent_param or (param != "_output_nonlinearity" and param in colormaps):
            # Create a colorbar axis on the right side of the corresponding row
            cbar_ax = fig.add_axes([0.92, 0.75 - (i * 0.75 / len(parameters)), 0.01, 0.5 / len(parameters)])
            
            if param == latent_param:
                # For latent size parameter
                cbar = fig.colorbar(colormaps[param]['sm'], cax=cbar_ax)
                cbar.set_label("Normalized Latent Size (0-1)")
            else:
                # For other numeric parameters
                cbar = fig.colorbar(colormaps[param]['sm'], cax=cbar_ax)
                cbar.set_label(param)
    
    # Create a common legend for model types
    handles = [plt.Line2D([0], [0], marker=marker, color='w', markerfacecolor='gray', 
                          markersize=8, label=model_type) 
               for model_type, marker in model_markers.items()]
    
    # Add handles for output nonlinearity values if that parameter exists
    if "_output_nonlinearity" in parameters and "_output_nonlinearity" in df.columns:
        nonlinearity_handles = [plt.Line2D([0], [0], color=color, lw=4, label=str(nl_type)) 
                               for nl_type, color in categorical_colors.items() 
                               if nl_type in df["_output_nonlinearity"].values or pd.isna(nl_type) and df["_output_nonlinearity"].isna().any()]
        handles.extend(nonlinearity_handles)
    
    # Add a handle for the error bars
    error_handle = plt.Line2D([0], [0], color='black', lw=1, marker='_', 
                             markersize=8, label='Standard Error', alpha=0.7)
    handles.append(error_handle)
    
    fig.legend(handles=handles, loc='upper center', bbox_to_anchor=(0.5, 0),
               ncol=min(len(handles), 4), title="Model Types & Parameters", fontsize=10)
    
    # Adjust layout with space for colorbars on right
    plt.subplots_adjust(right=0.9, bottom=0.15, wspace=0.3, hspace=0.3)
    
    if output_filepath:
        plt.savefig(output_filepath, bbox_inches='tight', dpi=dpi)
        print(f"High-resolution figure saved to {output_filepath}")
    else:
        plt.show()
    
    return fig