_target_: ctd.data_modeling.models.SAE.LDS.LDSSAE
dataset: MultiTask

encoder_size: 100
encoder_window: -1

heldin_size: 50
heldout_size: 50
latent_size: 128
input_size: 20

weight_decay: 0
lr: 1e-4

dropout: 0.05
loss_func:
  _target_: ctd.data_modeling.models.SAE.loss_func.MultiTaskPoissonLossFunc
