_target_: ctd.data_modeling.models.SAE.node.NODELatentSAE
dataset: MultiTask

encoder_size: 100
encoder_window: -1

heldin_size: 50
heldout_size: 60
latent_size: 20
input_size: 20

dropout: 0.05

vf_hidden_size: 128
vf_num_layers: 6

lr: 2e-3

weight_decay: 1e-7

loss_func:
  _target_: ctd.data_modeling.models.SAE.loss_func.MultiTaskPoissonLossFunc
